# Generated by Django 2.2.16 on 2022-09-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user', 'author'), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
